import React from "react";
import Head from "next/head";
import { useGetTodosQuery } from "@/__generated__/graphql";
import { Layout } from "@/components/Layout/Layout";

export default function Home() {
  const { data, loading, error } = useGetTodosQuery();
  return (
    <Layout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1 className="text-3xl">Hello world!</h1>
        <div>{loading && <p>Loading...</p>}</div>
        <div>
          {data?.getTodos?.todos?.map((todo) => (
            <div key={todo?.id}>
              <p>{todo?.title}</p>
              <p>{todo?.createdAt.toISOString()}</p>
            </div>
          ))}
        </div>
      </main>
    </Layout>
  );
}
